services:
  api:
    build: ./back
    container_name: task_api
    ports:
      - "3000:3000"
    volumes:
      - ./back:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${PORT:-3000}
      - CORS_ORIGIN=${CORS_ORIGIN:-http://localhost:5173}

  client:
    build: ./front
    container_name: task_client
    ports:
      - "5173:5173"
    volumes:
      - ./front:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:3000}
    depends_on:
      - api
