FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM node:22-alpine AS production

RUN addgroup app && adduser -S -G app app
WORKDIR /app

COPY package*.json ./
RUN npm ci --omit=dev

COPY --from=build /app/dist ./dist

RUN chown -R app:app /app
USER app

EXPOSE 3000

CMD ["node", "dist/index.js"]
